spring.application.name=servicioTecnico


spring.datasource.url=jdbc:mysql://localhost:3306/db_tiendaMusical
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Futura conexion con cliente y producto ***RECORDAR CAMBIAR LOS PUERTOS DE SER NECESARIO***
cliente.service.url=http://localhost:8081/api/clientes
producto.service.url=http://localhost:8082/api/productos