server:
  port: 8082

spring:
  application:
    name: Clientes

  datasource:
    url: jdbc:mysql://localhost:3306/db_tiendamusical
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver


  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history_reclamos

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: laClaveDeLaTiendaDeMusicaEstanLargaLoSuficiente

cliente-service:
  url: http://localhost:8081/api/clientes